"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const node_fs_1 = require("node:fs");
const node_path_1 = require("node:path");
const vitest_1 = require("./vitest-shim");
const break_signature_1 = require("../../lib/iris/services/maintain/break-signature");
const wer_signature_fixture_1 = require("./fixtures/wer-signature-fixture");
const TAURI = "tauri";
const ELECTRON = "electron";
(0, vitest_1.describe)("normalizeSymbol", () => {
    (0, vitest_1.it)("replaces a hex address with the placeholder", () => {
        (0, vitest_1.expect)((0, break_signature_1.normalizeSymbol)("cue::render_frame + 0x1a2b3c")).toBe("cue::render_frame + <x>");
    });
    (0, vitest_1.it)("replaces a trailing offset", () => {
        (0, vitest_1.expect)((0, break_signature_1.normalizeSymbol)("cue::render_frame + 42")).toBe("cue::render_frame <x>");
    });
    (0, vitest_1.it)("replaces a Rust v0/legacy generic-instantiation hash, consuming the leading '::'", () => {
        (0, vitest_1.expect)((0, break_signature_1.normalizeSymbol)("cue::render::h9f8e7d6c5b4a3210")).toBe("cue::render<x>");
    });
    (0, vitest_1.it)("replaces mangling residue", () => {
        (0, vitest_1.expect)((0, break_signature_1.normalizeSymbol)("_ZN3cue6render$abcdef1234E")).toBe("_ZN3cue6render<x>E");
    });
    (0, vitest_1.it)("trims surrounding whitespace but does not touch closure nesting or argument labels", () => {
        // Deliberately NOT stripped: closure nesting and argument labels — see
        // the function's own doc comment for why they distinguish genuinely
        // different call sites.
        (0, vitest_1.expect)((0, break_signature_1.normalizeSymbol)("  cue::save(path:) closure #1  ")).toBe("cue::save(path:) closure #1");
    });
    (0, vitest_1.it)("leaves a plain symbol with no volatile parts untouched", () => {
        (0, vitest_1.expect)((0, break_signature_1.normalizeSymbol)("cue::main")).toBe("cue::main");
    });
});
(0, vitest_1.describe)("normalizeMessage", () => {
    (0, vitest_1.it)("lowercases", () => {
        (0, vitest_1.expect)((0, break_signature_1.normalizeMessage)("Access Violation")).toBe("access violation");
    });
    (0, vitest_1.it)("replaces a uuid", () => {
        (0, vitest_1.expect)((0, break_signature_1.normalizeMessage)("session a1b2c3d4-e5f6-7890-abcd-ef1234567890 failed")).toBe("session <uuid> failed");
    });
    (0, vitest_1.it)("replaces a 0x-prefixed address", () => {
        (0, vitest_1.expect)((0, break_signature_1.normalizeMessage)("fault at 0x00007ff6a1b2c3d4")).toBe("fault at <addr>");
    });
    (0, vitest_1.it)("replaces a bare hex run of 7+ characters", () => {
        (0, vitest_1.expect)((0, break_signature_1.normalizeMessage)("thread id abcdef1")).toBe("thread id <hex>");
    });
    (0, vitest_1.it)("replaces a Windows path before it can fall into the posix path pattern", () => {
        (0, vitest_1.expect)((0, break_signature_1.normalizeMessage)(String.raw `failed to write C:\Users\alice\AppData\Local\cue\log.txt`)).toBe("failed to write <path>");
    });
    (0, vitest_1.it)("replaces a posix-shaped path", () => {
        (0, vitest_1.expect)((0, break_signature_1.normalizeMessage)("failed to read /home/alice/.config/cue/settings.json")).toBe("failed to read <path>");
    });
    (0, vitest_1.it)("replaces bare numbers", () => {
        (0, vitest_1.expect)((0, break_signature_1.normalizeMessage)("retry 3 of 5 after 1200ms")).toBe("retry <n> of <n> after <n>ms");
    });
    (0, vitest_1.it)("collapses whitespace runs and trims", () => {
        (0, vitest_1.expect)((0, break_signature_1.normalizeMessage)("  too    many     spaces  ")).toBe("too many spaces");
    });
    (0, vitest_1.it)("caps normalized output at 300 characters", () => {
        const longMessage = "x".repeat(500);
        const normalized = (0, break_signature_1.normalizeMessage)(longMessage);
        (0, vitest_1.expect)(normalized.length).toBe(300);
    });
});
(0, vitest_1.describe)("normalizeMessage parity with publik's normalizeBreakMessage", () => {
    // This used to import publik's `lib/break-signature` directly and assert the
    // two implementations agreed, deliberately without hand-written expectations.
    // Splitting the desktop clients out of publik made that import reach outside
    // the repository, which broke the typecheck and with it every Windows job.
    //
    // The property still matters — the pool splits one break into two buckets if
    // these normalizers disagree, because the web listing pages and the Windows
    // client each compute a signature client-side before the server sees it. So
    // rather than drop the check, the right-hand column below was GENERATED by
    // running publik's real `normalizeBreakMessage` over these exact vectors on
    // 2026-08-25. They are its output, not a transcription.
    //
    // The limitation is honest: this catches Windows drifting, and cannot catch
    // publik drifting, because nothing in this repository can see that code any
    // more. Regenerate this table whenever publik's normalizer changes.
    const publikOutputForVector = [
        ["", ""],
        ["Access Violation", "access violation"],
        [
            "session a1b2c3d4-e5f6-7890-abcd-ef1234567890 failed at 0x00007ff6a1b2c3d4",
            "session <uuid> failed at <addr>",
        ],
        [String.raw `failed to write C:\Users\alice\AppData\Local\cue\log.txt`, "failed to write <path>"],
        ["failed to read /home/alice/.config/cue/settings.json", "failed to read <path>"],
        ["retry 3 of 5 after 1200ms, thread abcdef1", "retry <n> of <n> after <n>ms, thread <hex>"],
        ["  too    many     spaces  ", "too many spaces"],
        [
            "MIXED Case Message With 123 Numbers And UUID a1b2c3d4-e5f6-7890-abcd-ef1234567890",
            "mixed case message with <n> numbers and uuid <uuid>",
        ],
        ["x".repeat(500), "x".repeat(300)],
        ["no volatile parts here at all", "no volatile parts here at all"],
        [
            String.raw `nested C:\Users\bob\proj\src\main.rs panicked, see /var/log/cue/crash-2024.log for 0xdeadbeef`,
            "nested <path> panicked, see <path> for <addr>",
        ],
    ];
    vitest_1.it.each(publikOutputForVector)("normalizes %j the way publik does", (rawMessage, expected) => {
        (0, vitest_1.expect)((0, break_signature_1.normalizeMessage)(rawMessage)).toBe(expected);
    });
});
(0, vitest_1.describe)("truncatedSha256", () => {
    (0, vitest_1.it)("returns 32 lowercase hex characters", () => {
        const hash = (0, break_signature_1.truncatedSha256)("cue|electron|native-crash|cue.exe!offset:<x>");
        (0, vitest_1.expect)(hash).toMatch(/^[0-9a-f]{32}$/);
    });
    (0, vitest_1.it)("is deterministic for the same input", () => {
        (0, vitest_1.expect)((0, break_signature_1.truncatedSha256)("same composite")).toBe((0, break_signature_1.truncatedSha256)("same composite"));
    });
    (0, vitest_1.it)("differs for a different input", () => {
        (0, vitest_1.expect)((0, break_signature_1.truncatedSha256)("composite a")).not.toBe((0, break_signature_1.truncatedSha256)("composite b"));
    });
});
(0, vitest_1.describe)("parseWerReportForSignature", () => {
    (0, vitest_1.it)("reads every Sig[] identity field out of a fully-populated report", () => {
        const parsed = (0, break_signature_1.parseWerReportForSignature)(wer_signature_fixture_1.CUE_APPCRASH_WER_FIXTURE);
        (0, vitest_1.expect)(parsed.appName).toBe("cue.exe");
        (0, vitest_1.expect)(parsed.appVersion).toBe("0.2.3.0");
        (0, vitest_1.expect)(parsed.faultingModuleName).toBe("cue.exe");
        (0, vitest_1.expect)(parsed.faultingModuleVersion).toBe("0.2.3.0");
        (0, vitest_1.expect)(parsed.exceptionCode).toBe("c0000005");
        (0, vitest_1.expect)(parsed.faultingOffset).toBe("0000000000012345");
        (0, vitest_1.expect)(parsed.reportId).toBe("a1b2c3d4-1234-5678-9abc-def012345678");
        (0, vitest_1.expect)(parsed.appPath).toBe("C:\\Users\\test\\AppData\\Local\\Programs\\cue\\cue.exe");
    });
    (0, vitest_1.it)("stops reading at the first bracketed section header", () => {
        // The fixture appends a fake Sig[99] pair after `[dynamic data]` whose
        // values would fail every other assertion in this describe block if the
        // parser kept reading past the section header.
        const parsed = (0, break_signature_1.parseWerReportForSignature)(wer_signature_fixture_1.CUE_APPCRASH_WER_FIXTURE);
        (0, vitest_1.expect)(parsed.faultingModuleName).not.toBe("Should Never Be Read");
    });
    (0, vitest_1.it)("normalizes an upper-case 0x-prefixed hex field to the same value as the unprefixed lower-case spelling", () => {
        const prefixed = (0, break_signature_1.parseWerReportForSignature)(wer_signature_fixture_1.CUE_APPCRASH_WER_FIXTURE_HEX_PREFIXED);
        const unprefixed = (0, break_signature_1.parseWerReportForSignature)(wer_signature_fixture_1.CUE_APPCRASH_WER_FIXTURE);
        (0, vitest_1.expect)(prefixed.exceptionCode).toBe(unprefixed.exceptionCode);
        (0, vitest_1.expect)(prefixed.faultingOffset).toBe(unprefixed.faultingOffset);
        (0, vitest_1.expect)(prefixed.exceptionCode).toBe("c0000005");
    });
    (0, vitest_1.it)("collects a Sig[N] pair regardless of whether Value or Name arrives first", () => {
        const parsed = (0, break_signature_1.parseWerReportForSignature)(wer_signature_fixture_1.REORDERED_SIG_FIELDS_WER_FIXTURE);
        (0, vitest_1.expect)(parsed.appName).toBe("cue.exe");
        (0, vitest_1.expect)(parsed.exceptionCode).toBe("c0000005");
    });
    (0, vitest_1.it)("falls back to the flat AppName field when the Sig[] block is entirely absent", () => {
        const parsed = (0, break_signature_1.parseWerReportForSignature)(wer_signature_fixture_1.MINIMAL_WER_FIXTURE_WITH_FLAT_APPNAME_ONLY);
        (0, vitest_1.expect)(parsed.appName).toBe("fallback-app.exe");
        (0, vitest_1.expect)(parsed.faultingModuleName).toBeUndefined();
        (0, vitest_1.expect)(parsed.exceptionCode).toBeUndefined();
    });
    (0, vitest_1.it)("falls back to unknown.exe and undefined fields when nothing at all is present", () => {
        const parsed = (0, break_signature_1.parseWerReportForSignature)(wer_signature_fixture_1.EMPTY_WER_FIXTURE);
        (0, vitest_1.expect)(parsed.appName).toBe("unknown.exe");
        (0, vitest_1.expect)(parsed.appVersion).toBeUndefined();
        (0, vitest_1.expect)(parsed.faultingModuleName).toBeUndefined();
        (0, vitest_1.expect)(parsed.exceptionCode).toBeUndefined();
        (0, vitest_1.expect)(parsed.reportId).toBeUndefined();
    });
    (0, vitest_1.it)("ignores a blank line and a malformed line with no '=' separator", () => {
        const text = ["Version=1", "", "this line has no separator", "Sig[0].Name=Application Name", "Sig[0].Value=cue.exe"].join("\r\n");
        const parsed = (0, break_signature_1.parseWerReportForSignature)(text);
        (0, vitest_1.expect)(parsed.appName).toBe("cue.exe");
    });
    (0, vitest_1.it)("round-trips through buildAppCrashWerText for an app whose name has no matching fault module", () => {
        const text = (0, wer_signature_fixture_1.buildAppCrashWerText)({ applicationName: "other.exe", faultModuleName: "ntdll.dll" });
        const parsed = (0, break_signature_1.parseWerReportForSignature)(text);
        (0, vitest_1.expect)(parsed.appName).toBe("other.exe");
        (0, vitest_1.expect)(parsed.faultingModuleName).toBe("ntdll.dll");
    });
});
(0, vitest_1.describe)("nativeCrashSignature", () => {
    (0, vitest_1.it)("builds exactly one synthetic frame from the fault module and offset", () => {
        const parsed = (0, break_signature_1.parseWerReportForSignature)(wer_signature_fixture_1.CUE_APPCRASH_WER_FIXTURE);
        const signature = (0, break_signature_1.nativeCrashSignature)(parsed, "cue", ELECTRON);
        (0, vitest_1.expect)(signature.kind).toBe("native-crash");
        (0, vitest_1.expect)(signature.algoVersion).toBe(break_signature_1.WINDOWS_SIGNATURE_ALGO_VERSION);
        (0, vitest_1.expect)(signature.appSlug).toBe("cue");
        (0, vitest_1.expect)(signature.appStack).toBe(ELECTRON);
        (0, vitest_1.expect)(signature.topFrames).toHaveLength(1);
        (0, vitest_1.expect)(signature.topFrames[0]?.module).toBe("cue.exe");
        (0, vitest_1.expect)(signature.topFrames[0]?.sourceFile).toBeNull();
        (0, vitest_1.expect)(signature.topFrames[0]?.function).toContain("offset:");
    });
    (0, vitest_1.it)("marks the frame as an application frame when the fault module matches the app name", () => {
        const parsed = (0, break_signature_1.parseWerReportForSignature)(wer_signature_fixture_1.CUE_APPCRASH_WER_FIXTURE);
        const signature = (0, break_signature_1.nativeCrashSignature)(parsed, "cue", ELECTRON);
        (0, vitest_1.expect)(signature.topFrames[0]?.isApplicationFrame).toBe(true);
    });
    (0, vitest_1.it)("marks the frame as NOT an application frame when the crash is inside a system module", () => {
        const parsed = (0, break_signature_1.parseWerReportForSignature)(wer_signature_fixture_1.CUE_APPCRASH_WER_FIXTURE_FOREIGN_MODULE);
        const signature = (0, break_signature_1.nativeCrashSignature)(parsed, "cue", ELECTRON);
        (0, vitest_1.expect)(signature.topFrames[0]?.isApplicationFrame).toBe(false);
        (0, vitest_1.expect)(signature.topFrames[0]?.module).toBe("KERNELBASE.dll");
    });
    (0, vitest_1.it)("falls back to UNKNOWN_EXCEPTION and unknown-module when the report has neither", () => {
        const parsed = (0, break_signature_1.parseWerReportForSignature)(wer_signature_fixture_1.EMPTY_WER_FIXTURE);
        const signature = (0, break_signature_1.nativeCrashSignature)(parsed, "cue", ELECTRON);
        (0, vitest_1.expect)(signature.protoSignature).toContain("UNKNOWN_EXCEPTION");
        (0, vitest_1.expect)(signature.topFrames[0]?.module).toBe("unknown-module");
        (0, vitest_1.expect)(signature.fingerprintLoose).toBe("unknown-module");
    });
    (0, vitest_1.it)("is deterministic: the same crash on the same app produces the same signatureId", () => {
        const parsed = (0, break_signature_1.parseWerReportForSignature)(wer_signature_fixture_1.CUE_APPCRASH_WER_FIXTURE);
        const first = (0, break_signature_1.nativeCrashSignature)(parsed, "cue", ELECTRON);
        const second = (0, break_signature_1.nativeCrashSignature)(parsed, "cue", ELECTRON);
        (0, vitest_1.expect)(first.signatureId).toBe(second.signatureId);
        (0, vitest_1.expect)(first.fingerprintStrict).toBe(second.fingerprintStrict);
    });
    (0, vitest_1.it)("gives the hex-prefixed and unprefixed fixtures the same signatureId, since normalizeHexField equalizes them", () => {
        const prefixed = (0, break_signature_1.nativeCrashSignature)((0, break_signature_1.parseWerReportForSignature)(wer_signature_fixture_1.CUE_APPCRASH_WER_FIXTURE_HEX_PREFIXED), "cue", ELECTRON);
        // Build a comparable unprefixed report with the same app/module/offset as
        // the hex-prefixed fixture (CUE_APPCRASH_WER_FIXTURE has an extra
        // Application Version field the hex-prefixed one omits, which would
        // otherwise make this comparison compare two different reports).
        const unprefixedEquivalent = (0, break_signature_1.nativeCrashSignature)((0, break_signature_1.parseWerReportForSignature)((0, wer_signature_fixture_1.buildAppCrashWerText)({
            applicationName: "cue.exe",
            faultModuleName: "cue.exe",
            exceptionCode: "c0000005",
            exceptionOffset: "0000000000012345",
            reportIdentifier: "a1b2c3d4-1234-5678-9abc-def012345678",
        })), "cue", ELECTRON);
        (0, vitest_1.expect)(prefixed.signatureId).toBe(unprefixedEquivalent.signatureId);
    });
    (0, vitest_1.it)("gives two different apps different signatures for the identical crash shape", () => {
        const parsed = (0, break_signature_1.parseWerReportForSignature)(wer_signature_fixture_1.CUE_APPCRASH_WER_FIXTURE);
        const cueSignature = (0, break_signature_1.nativeCrashSignature)(parsed, "cue", ELECTRON);
        const otherAppSignature = (0, break_signature_1.nativeCrashSignature)(parsed, "some-other-app", ELECTRON);
        (0, vitest_1.expect)(cueSignature.signatureId).not.toBe(otherAppSignature.signatureId);
    });
    (0, vitest_1.it)("uses the fault module name alone as fingerprintLoose, the honest Windows analog of function-only", () => {
        const parsed = (0, break_signature_1.parseWerReportForSignature)(wer_signature_fixture_1.CUE_APPCRASH_WER_FIXTURE_FOREIGN_MODULE);
        const signature = (0, break_signature_1.nativeCrashSignature)(parsed, "cue", ELECTRON);
        (0, vitest_1.expect)(signature.fingerprintLoose).toBe("KERNELBASE.dll");
    });
});
(0, vitest_1.describe)("hangSignature", () => {
    (0, vitest_1.it)("uses main-thread as the frame when no blocked frame is known", () => {
        const signature = (0, break_signature_1.hangSignature)("cue", ELECTRON, null);
        (0, vitest_1.expect)(signature.kind).toBe("hang");
        (0, vitest_1.expect)(signature.fingerprintLoose).toBe("main-thread");
        (0, vitest_1.expect)(signature.topFrames).toEqual([]);
    });
    (0, vitest_1.it)("normalizes a known blocked frame through normalizeSymbol", () => {
        const signature = (0, break_signature_1.hangSignature)("cue", ELECTRON, "cue::wait_for(ms: 0x1a2b3c)");
        (0, vitest_1.expect)(signature.fingerprintLoose).toBe("cue::wait_for(ms: <x>)");
    });
    (0, vitest_1.it)("differs from a native-crash signature for the same app, since kind rides in the composite", () => {
        const parsed = (0, break_signature_1.parseWerReportForSignature)(wer_signature_fixture_1.CUE_APPCRASH_WER_FIXTURE);
        const crashSignature = (0, break_signature_1.nativeCrashSignature)(parsed, "cue", ELECTRON);
        const hangSig = (0, break_signature_1.hangSignature)("cue", ELECTRON, null);
        (0, vitest_1.expect)(hangSig.signatureId).not.toBe(crashSignature.signatureId);
    });
});
(0, vitest_1.describe)("rustPanicSignature", () => {
    (0, vitest_1.it)("parses the old-style panic format (quoted message, trailing location)", () => {
        const stderr = "thread 'main' panicked at 'index out of bounds: the len is 3 but the index is 5', src/main.rs:42:9";
        const signature = (0, break_signature_1.rustPanicSignature)("cue", TAURI, stderr);
        (0, vitest_1.expect)(signature.kind).toBe("rust-panic");
        (0, vitest_1.expect)(signature.fingerprintStrict).toContain("src/main.rs");
        (0, vitest_1.expect)(signature.fingerprintLoose).toBe("index out of bounds: the len is <n> but the index is <n>");
    });
    (0, vitest_1.it)("parses the new-style panic format (location first, message on the next line)", () => {
        const stderr = "thread 'main' panicked at src/lib.rs:17:5:\nassertion failed: cache.is_some()";
        const signature = (0, break_signature_1.rustPanicSignature)("cue", TAURI, stderr);
        (0, vitest_1.expect)(signature.fingerprintStrict).toContain("src/lib.rs");
        (0, vitest_1.expect)(signature.fingerprintLoose).toBe("assertion failed: cache.is_some()");
    });
    (0, vitest_1.it)("falls back to unknown.rs when no file:line location is present", () => {
        const signature = (0, break_signature_1.rustPanicSignature)("cue", TAURI, "something went very wrong with no location");
        (0, vitest_1.expect)(signature.fingerprintStrict).toContain("unknown.rs");
    });
    (0, vitest_1.it)("normalizes volatile parts of the panic message", () => {
        const stderr = "panicked at src/db.rs:9:1:\nfailed to open /home/alice/.cue/db-a1b2c3d4-e5f6-7890-abcd-ef1234567890.sqlite";
        const signature = (0, break_signature_1.rustPanicSignature)("cue", TAURI, stderr);
        (0, vitest_1.expect)(signature.fingerprintLoose).toBe("failed to open <path>");
    });
});
(0, vitest_1.describe)("electronRendererGoneSignature", () => {
    (0, vitest_1.it)("is categorical: no topFrames, and the reason carries the identity", () => {
        const signature = (0, break_signature_1.electronRendererGoneSignature)("cue", "crashed");
        (0, vitest_1.expect)(signature.kind).toBe("js-exception");
        (0, vitest_1.expect)(signature.appStack).toBe("electron");
        (0, vitest_1.expect)(signature.topFrames).toEqual([]);
        (0, vitest_1.expect)(signature.fingerprintLoose).toBe("renderer-gone|crashed");
    });
    (0, vitest_1.it)("normalizes the reason like any other message", () => {
        const signature = (0, break_signature_1.electronRendererGoneSignature)("cue", "OOM after 12345ms");
        (0, vitest_1.expect)(signature.fingerprintLoose).toBe("renderer-gone|oom after <n>ms");
    });
    vitest_1.it.each(["crashed", "oom", "killed", "launch-failed"])("distinguishes Chromium's own reason %s from the others", (reason) => {
        const signature = (0, break_signature_1.electronRendererGoneSignature)("cue", reason);
        const otherReasons = ["crashed", "oom", "killed", "launch-failed"].filter((candidate) => candidate !== reason);
        for (const otherReason of otherReasons) {
            (0, vitest_1.expect)(signature.signatureId).not.toBe((0, break_signature_1.electronRendererGoneSignature)("cue", otherReason).signatureId);
        }
    });
});
(0, vitest_1.describe)("outOfMemorySignature", () => {
    (0, vitest_1.it)("has no stack and a fixed categorical identity", () => {
        const signature = (0, break_signature_1.outOfMemorySignature)("cue", ELECTRON);
        (0, vitest_1.expect)(signature.kind).toBe("oom");
        (0, vitest_1.expect)(signature.topFrames).toEqual([]);
        (0, vitest_1.expect)(signature.fingerprintStrict).toBe("oom");
        (0, vitest_1.expect)(signature.fingerprintLoose).toBe("oom");
    });
    (0, vitest_1.it)("still distinguishes apps and stacks, since both ride in the composite", () => {
        const cueSignature = (0, break_signature_1.outOfMemorySignature)("cue", ELECTRON);
        const otherAppSignature = (0, break_signature_1.outOfMemorySignature)("other-app", ELECTRON);
        const otherStackSignature = (0, break_signature_1.outOfMemorySignature)("cue", TAURI);
        (0, vitest_1.expect)(cueSignature.signatureId).not.toBe(otherAppSignature.signatureId);
        (0, vitest_1.expect)(cueSignature.signatureId).not.toBe(otherStackSignature.signatureId);
    });
});
(0, vitest_1.describe)("launchFailureSignature", () => {
    (0, vitest_1.it)("carries the daemon (exe name) and the normalized reason", () => {
        const signature = (0, break_signature_1.launchFailureSignature)("cue", ELECTRON, "cue.exe", "spawn ENOENT");
        (0, vitest_1.expect)(signature.kind).toBe("launch-failure");
        (0, vitest_1.expect)(signature.fingerprintStrict).toBe("launch|cue.exe|spawn enoent");
        (0, vitest_1.expect)(signature.fingerprintLoose).toBe("launch|cue.exe");
    });
    (0, vitest_1.it)("normalizes the reason the same way every other kind does", () => {
        const signature = (0, break_signature_1.launchFailureSignature)("cue", ELECTRON, "cue.exe", String.raw `spawn C:\Users\alice\AppData\Local\Programs\cue\cue.exe ENOENT`);
        (0, vitest_1.expect)(signature.fingerprintStrict).toBe("launch|cue.exe|spawn <path> enoent");
    });
    (0, vitest_1.it)("fingerprintLoose absorbs a changed reason but not a changed daemon", () => {
        const first = (0, break_signature_1.launchFailureSignature)("cue", ELECTRON, "cue.exe", "spawn ENOENT");
        const second = (0, break_signature_1.launchFailureSignature)("cue", ELECTRON, "cue.exe", "permission denied");
        (0, vitest_1.expect)(first.fingerprintLoose).toBe(second.fingerprintLoose);
        const differentDaemon = (0, break_signature_1.launchFailureSignature)("cue", ELECTRON, "cue-helper.exe", "spawn ENOENT");
        (0, vitest_1.expect)(first.fingerprintLoose).not.toBe(differentDaemon.fingerprintLoose);
    });
});
(0, vitest_1.describe)("BreakAppStack wire vocabulary", () => {
    (0, vitest_1.it)("keeps swift-macos in the union even though this client never emits it", () => {
        // A compile-time assertion as much as a runtime one: if `BreakAppStack`
        // ever drops this member, this line stops compiling. See the module
        // header for why dropping it would make the type lie about what the
        // server's `signatures.app_stack` check constraint accepts.
        const swiftMacOsStack = "swift-macos";
        const signature = (0, break_signature_1.outOfMemorySignature)("some-app", swiftMacOsStack);
        (0, vitest_1.expect)(signature.appStack).toBe("swift-macos");
    });
});
// ---------------------------------------------------------------------------
// DETECTION, against real `Report.wer` files on disk — the Windows analog of
// the Swift maintain-mode test harness's D1–D3
// (`gemair-macos/tools/maintain-test-harness/main.swift`, which reads
// `swift-crash-A.ips` / `swift-crash-different-bug.ips` off disk the same
// way). `wer-signature-fixture.ts`'s `buildAppCrashWerText` helper already
// exercises the parser thoroughly with in-memory strings (every field
// individually, malformed lines, reordered Sig[] pairs, …) — this block's
// job is narrower and complementary: prove the parser + signature builder
// behave correctly against REAL FILES read with `node:fs`, exactly the kind
// of artifact `crash-watcher.ts`'s sure path finds on a real machine, and
// walk through the harness's specific dedup/distinguish narrative using
// them.
//
// Fixture files use plain LF line endings (unlike `buildAppCrashWerText`,
// which deliberately renders CRLF — see that file's header). That CRLF
// property is already covered there; duplicating it here would test nothing
// new. `parseWerReportForSignature` splits on `/\r?\n/` and trims each line,
// so either ending parses identically — see its own header comment.
// ---------------------------------------------------------------------------
function readWerFixture(fileName) {
    return (0, node_fs_1.readFileSync)((0, node_path_1.join)(__dirname, "fixtures", fileName), "utf-8");
}
(0, vitest_1.describe)("parseWerReportForSignature / nativeCrashSignature — against real .wer fixture files on disk", () => {
    (0, vitest_1.it)("parses a real Report.wer file and builds a correctly-kinded, 32-hex signature", () => {
        const parsed = (0, break_signature_1.parseWerReportForSignature)(readWerFixture("crash-cue-bug-a.wer"));
        (0, vitest_1.expect)(parsed.appName).toBe("cue.exe");
        (0, vitest_1.expect)(parsed.faultingModuleName).toBe("cue.exe");
        (0, vitest_1.expect)(parsed.exceptionCode).toBe("c0000005");
        const signature = (0, break_signature_1.nativeCrashSignature)(parsed, "cue", ELECTRON);
        (0, vitest_1.expect)(signature.kind).toBe("native-crash");
        (0, vitest_1.expect)(signature.signatureId).toMatch(/^[0-9a-f]{32}$/);
        (0, vitest_1.expect)(signature.topFrames).toHaveLength(1);
    });
    (0, vitest_1.it)("the Windows analog of 'caller, not runtime': the identity names the module that actually " +
        "faulted, and tags whether that module is the app's own code or a system module — there is " +
        "no walked stack to skip past (WER gives one fault point, never a call stack; see the module " +
        "header's 'Windows has no .ips, no ReportCrash, no walked stack')", () => {
        const appFrame = (0, break_signature_1.nativeCrashSignature)((0, break_signature_1.parseWerReportForSignature)(readWerFixture("crash-cue-bug-a.wer")), "cue", ELECTRON);
        (0, vitest_1.expect)(appFrame.topFrames[0].isApplicationFrame).toBe(true);
        (0, vitest_1.expect)(appFrame.topFrames[0].module).toBe("cue.exe");
        const systemModuleFrame = (0, break_signature_1.nativeCrashSignature)((0, break_signature_1.parseWerReportForSignature)(readWerFixture("crash-cue-system-module.wer")), "cue", ELECTRON);
        (0, vitest_1.expect)(systemModuleFrame.topFrames[0].isApplicationFrame).toBe(false);
        (0, vitest_1.expect)(systemModuleFrame.topFrames[0].module).toBe("ntdll.dll");
        // Both are still real, valid native-crash signatures for the same app —
        // the isApplicationFrame tag is metadata riding along, never a reason
        // to refuse to compute an identity.
        (0, vitest_1.expect)(systemModuleFrame.signatureId).toMatch(/^[0-9a-f]{32}$/);
        (0, vitest_1.expect)(appFrame.signatureId).not.toBe(systemModuleFrame.signatureId);
    });
    (0, vitest_1.it)("dedups: two real captures of the SAME bug (identical module + exception code, different address/report id/timestamp) collapse to the same loose fingerprint and the same signatureId", () => {
        const first = (0, break_signature_1.nativeCrashSignature)((0, break_signature_1.parseWerReportForSignature)(readWerFixture("crash-cue-bug-a.wer")), "cue", ELECTRON);
        const second = (0, break_signature_1.nativeCrashSignature)((0, break_signature_1.parseWerReportForSignature)(readWerFixture("crash-cue-bug-a-recurrence.wer")), "cue", ELECTRON);
        (0, vitest_1.expect)(first.fingerprintLoose).toBe(second.fingerprintLoose);
        // Windows has no symbol table on this client (see the module header): a
        // bare offset carries no diagnostic weight, so `normalizeSymbol` collapses
        // it to the same placeholder regardless of its actual value, and two
        // captures of the same underlying bug therefore land on the same
        // signatureId too, not merely the same loose fingerprint. This is the
        // documented, honest coarseness of a client with no walked stack — see
        // "uses the fault module name alone as fingerprintLoose" above.
        (0, vitest_1.expect)(first.signatureId).toBe(second.signatureId);
    });
    (0, vitest_1.it)("distinguishes a genuinely different real bug (different fault module AND exception code) with both a different signatureId and a different loose fingerprint", () => {
        const bugA = (0, break_signature_1.nativeCrashSignature)((0, break_signature_1.parseWerReportForSignature)(readWerFixture("crash-cue-bug-a.wer")), "cue", ELECTRON);
        const differentBug = (0, break_signature_1.nativeCrashSignature)((0, break_signature_1.parseWerReportForSignature)(readWerFixture("crash-cue-different-bug.wer")), "cue", ELECTRON);
        (0, vitest_1.expect)(bugA.signatureId).not.toBe(differentBug.signatureId);
        (0, vitest_1.expect)(bugA.fingerprintLoose).not.toBe(differentBug.fingerprintLoose);
        (0, vitest_1.expect)(differentBug.topFrames[0].module).toBe("v8jsi.dll");
    });
    (0, vitest_1.it)("the same real crash text in a different app never shares a signature (identity always includes appSlug)", () => {
        const parsed = (0, break_signature_1.parseWerReportForSignature)(readWerFixture("crash-cue-bug-a.wer"));
        const asCue = (0, break_signature_1.nativeCrashSignature)(parsed, "cue", ELECTRON);
        const asLunara = (0, break_signature_1.nativeCrashSignature)(parsed, "lunara", ELECTRON);
        (0, vitest_1.expect)(asCue.signatureId).not.toBe(asLunara.signatureId);
    });
});
