// GemAir serverless — FREE CORE AI chat proxy (runs on Vercel).
//
// SECTION 0 — "KEY-FREE BY DEFAULT" (the Stonic Cloud pattern, at zero cost).
// Stonic advertises "connect your ChatGPT account — no API key needed" because
// THEIR server holds real API keys behind a proxy with Google sign-in + credit
// metering. GemAir's FREE CORE is the same idea without the account lock-in:
//
//   • Provider keys live ONLY in server env vars — the browser never sees them
//     and the end-user is never asked for one.
//   • The server tries a fallback chain of FREE providers (Groq free tier →
//     Gemini free tier → OpenRouter free models), so replies are almost always
//     generated by a real LLM at $0.
//   • 429 / rate-limit responses trigger automatic retry WITH provider rotation.
//   • SSE streaming is passed through when requested.
//   • Per-identity fair-use limits are enforced so the free tier stays usable.
//   • If no key is configured at all (or every provider fails), the endpoint
//     still answers with a built-in free conversational brain — the user ALWAYS
//     gets a helpful reply and never a "please enter a key" error.
//
// Optional AI_BASE_URL/AI_MODEL override any single provider (backward compat).

const KEY_ENV_NAMES = ['GROQ_API_KEY', 'OPENAI_API_KEY', 'AI_KEY', 'GROQ_KEY', 'VERCEL_GROQ_KEY'];

// Free provider fallback chain. Each entry is an OpenAI-compatible endpoint;
// a key under any of keyEnv makes it usable. `nativeHeader` is sent alongside
// Bearer where a provider wants its own auth header (Gemini).
const FREE_PROVIDERS = [
  {
    id: 'groq', free: true,
    base: 'https://api.groq.com/openai/v1',
    keyEnv: ['GROQ_API_KEY', 'GROQ_KEY', 'VERCEL_GROQ_KEY'],
    models: ['llama-3.3-70b-versatile', 'llama-3.1-8b-instant', 'llama3-8b-8192', 'mixtral-8x7b-32768']
  },
  {
    id: 'gemini', free: true,
    base: 'https://generativelanguage.googleapis.com/v1beta/openai',
    keyEnv: ['GEMINI_API_KEY', 'GEMINI_KEY', 'GOOGLE_AI_API_KEY', 'GOOGLE_GEMINI_API_KEY'],
    nativeHeader: 'x-goog-api-key',
    models: ['gemini-2.5-flash', 'gemini-2.0-flash', 'gemini-1.5-flash']
  },
  {
    id: 'openrouter', free: true,
    base: 'https://openrouter.ai/api/v1',
    keyEnv: ['OPENROUTER_API_KEY', 'OPENROUTER_KEY'],
    models: ['meta-llama/llama-3.3-70b-instruct', 'meta-llama/llama-3.1-8b-instruct', 'mistralai/mistral-7b-instruct']
  },
  {
    id: 'openai', free: false,
    base: 'https://api.openai.com/v1',
    keyEnv: ['OPENAI_API_KEY'],
    models: ['gpt-4o-mini']
  }
];

function env(key) {
  try { return String(process.env[key] || '').trim(); } catch { return ''; }
}

// Collect providers that have at least one key available. If the user set
// AI_BASE_URL (a specific provider like a local Ollama or a custom gateway),
// honor that first — it is the explicit, intentional choice.
function availableProviders() {
  const out = [];
  const baseOverride = env('AI_BASE_URL');
  const modelOverride = env('AI_MODEL');
  if (baseOverride) {
    const key = KEY_ENV_NAMES.map(env).find(Boolean) || '';
    out.push({ id: 'override', base: baseOverride.replace(/\/+$/, ''), key, models: modelOverride ? [modelOverride] : ['llama-3.3-70b-versatile'] });
  }
  for (const p of FREE_PROVIDERS) {
    const key = p.keyEnv.map(env).find(Boolean) || '';
    if (key) out.push({ ...p, key, base: p.base.replace(/\/+$/, '') });
  }
  return out;
}

function aiHeaders(provider, key) {
  const headers = { 'Content-Type': 'application/json' };
  if (key) headers['Authorization'] = 'Bearer ' + key;
  if (key && provider.nativeHeader) headers[provider.nativeHeader] = key;
  return headers;
}

// ---------------------------------------------------------------------------
// Per-identity fair-use limits (Section 0). Keyed by an explicit identity sent
// by the renderer (profile.userId) when available, otherwise by client IP.
// A daily cap keeps the free tier responsive; a friendly message is returned
// when it is hit (never an error, never a key prompt).
// ---------------------------------------------------------------------------
const _usage = new Map(); // `${day}:${identity}` -> count (per-instance best effort)
const FAIR_USE_DAILY = (() => { const n = parseInt(env('FAIR_USE_DAILY'), 10); return Number.isFinite(n) && n > 0 ? n : 200; })();

function identityFor(req, body) {
  // R10: a client-supplied userId alone was trivially rotated to reset the
  // daily cap, so the IP is always part of the identity.
  const fwd = req.headers && req.headers['x-forwarded-for'];
  const ip = fwd ? String(fwd).split(',')[0].trim().slice(0, 64)
    : (req.headers && req.headers['x-real-ip']) ? String(req.headers['x-real-ip']).trim().slice(0, 64)
    : 'unknown';
  if (body && body.userId && typeof body.userId === 'string' && body.userId.trim()) {
    return 'u:' + body.userId.trim().slice(0, 64) + '@' + ip;
  }
  return 'ip:' + ip;
}

function fairUseLeft(identity) {
  const day = new Date().toISOString().slice(0, 10);
  const key = day + ':' + identity;
  const count = _usage.get(key) || 0;
  const left = Math.max(0, FAIR_USE_DAILY - count);
  return { day, key, left, count };
}

function consumeFairUse(identity) {
  const { day, key, count } = fairUseLeft(identity);
  _usage.set(key, count + 1);
  // keep the map small: prune other days periodically
  if (_usage.size > 5000) {
    for (const k of _usage.keys()) if (!k.startsWith(day)) _usage.delete(k);
  }
  return count + 1;
}

// ---------------------------------------------------------------------------
// Free conversational brain — used when no server key is configured (or every
// provider failed), so replies are instant, friendly and never an error.
// ---------------------------------------------------------------------------
function freeBrain(raw) {
  const q = String(raw || '').trim();
  const t = q.toLowerCase();
  const time = new Date().toLocaleTimeString([], { hour: 'numeric', minute: '2-digit', hour12: true });

  if (!t) return "Hello! I'm Gem, your AI inside GemAir. Ask me anything — I'm listening.";
  if (/^(hi|hii+|hiii+|hello+|hey+|heyy+|yo+|salam|salaam|namaste|namaskar|good (morning|afternoon|evening))\b/.test(t))
    return `Hello! Gem here — always online and completely free. Try "weather in Mumbai", "bitcoin price" or "translate hello to hindi" — or just talk to me.`;
  if (/who are you|your name/.test(t))
    return "I'm Gem — the intelligence inside GemAir, your free personal AI. I can search the live web, check weather, track prices, translate languages, and keep you company.";
  if (/how are you/.test(t)) return 'Running smooth — and glad you asked. How are you doing?';
  if (/thank|thanks|shukriya|dhanyavad/.test(t)) return 'Anytime. That is what I am here for.';
  if (/what can you do|help|features|commands/.test(t))
    return 'I can search the live web, read the news, check weather anywhere, track crypto and exchange rates, translate languages, define words, do math, set reminders and notes — and just chat with you. What do you need?';
  if (/\btime\b|clock/.test(t)) return `The current time is ${time}.`;
  if (/\bdate\b|what day/.test(t)) return `Today is ${new Date().toLocaleDateString([], { weekday: 'long', year: 'numeric', month: 'long', day: 'numeric' })}.`;
  if (/joke/.test(t)) return "There are only 10 kinds of people: those who understand binary and those who don't.";

  const math = t.replace(/[^0-9+\-*/().\s]/g, '').match(/^\s*([\d.]+)\s*([+\-*/])\s*([\d.]+)\s*$/);
  if (math) {
    const [ , a, op, b ] = math;
    let out;
    switch (op) {
      case '+': out = Number(a) + Number(b); break;
      case '-': out = Number(a) - Number(b); break;
      case '*': out = Number(a) * Number(b); break;
      case '/': out = Number(b) === 0 ? 'undefined (cannot divide by zero)' : Number(a) / Number(b); break;
    }
    if (out !== undefined) return `${a} ${op} ${b} = ${out}`;
  }

  return `I'm here and listening. I can search the live web, check weather, prices, translations, definitions and more — try "weather in Mumbai" or "search latest AI news".`;
}

// ---------------------------------------------------------------------------
// R10 — hardening
//
// (a) Every upstream fetch gets an AbortController timeout. A hung provider
//     used to pin the serverless function until the platform killed it, so the
//     fallback chain never got a chance to rotate.
// (b) A light Origin/Referer allow-check plus per-IP throttling. Before this,
//     any script on the internet could POST here and burn the shared free
//     provider keys; fair-use was keyed on a client-supplied userId which is
//     trivially rotated.
// ---------------------------------------------------------------------------
const UPSTREAM_TIMEOUT_MS = (() => {
  const n = parseInt(env('AI_TIMEOUT_MS'), 10);
  return Number.isFinite(n) && n >= 2000 ? n : 20000;
})();

/** fetch() with a hard deadline. Rejects with a tagged error on timeout. */
async function fetchWithTimeout(url, options = {}, timeoutMs = UPSTREAM_TIMEOUT_MS) {
  const controller = new AbortController();
  const timer = setTimeout(() => controller.abort(), timeoutMs);
  try {
    return await fetch(url, { ...options, signal: controller.signal });
  } catch (e) {
    if (e && (e.name === 'AbortError' || /abort/i.test(e.message || ''))) {
      const err = new Error('timeout after ' + timeoutMs + 'ms');
      err.isTimeout = true;
      throw err;
    }
    throw e;
  } finally {
    clearTimeout(timer);
  }
}

/**
 * Hosts allowed to call the free core. Defaults cover the app's own origins;
 * ALLOWED_ORIGINS (comma-separated hostnames) extends it. Requests with NO
 * Origin/Referer are allowed — that is the desktop Electron app and curl-style
 * health checks, which we do not want to break — but they are throttled the
 * same as everyone else.
 */
function allowedHosts() {
  const extra = env('ALLOWED_ORIGINS').split(',').map((s) => s.trim().toLowerCase()).filter(Boolean);
  return [
    'gemair.vercel.app',
    'localhost', '127.0.0.1', '0.0.0.0',
    ...extra
  ];
}

function originAllowed(req) {
  const raw = (req.headers && (req.headers.origin || req.headers.referer)) || '';
  if (!raw) return { ok: true, origin: '' };           // native app / no browser origin
  let host = '';
  try { host = new URL(raw).hostname.toLowerCase(); } catch { return { ok: false, origin: raw }; }
  const list = allowedHosts();
  const ok = list.some((h) => host === h || host.endsWith('.' + h)) ||
    /\.vercel\.app$/.test(host) ||                     // preview deployments
    host.endsWith('.e2b.app');                         // sandboxed dev preview
  return { ok, origin: host };
}

/** Sliding-window per-IP throttle (best effort, per serverless instance). */
const _throttle = new Map(); // ip -> number[] (recent request timestamps)
const THROTTLE_WINDOW_MS = 60000;
const THROTTLE_MAX = (() => { const n = parseInt(env('THROTTLE_PER_MIN'), 10); return Number.isFinite(n) && n > 0 ? n : 12; })();

function clientIp(req) {
  const fwd = req.headers && req.headers['x-forwarded-for'];
  if (fwd) return String(fwd).split(',')[0].trim().slice(0, 64);
  const real = req.headers && req.headers['x-real-ip'];
  if (real) return String(real).trim().slice(0, 64);
  return (req.socket && req.socket.remoteAddress) || 'unknown';
}

function throttleCheck(ip) {
  const now = Date.now();
  const hits = (_throttle.get(ip) || []).filter((t) => now - t < THROTTLE_WINDOW_MS);
  if (hits.length >= THROTTLE_MAX) {
    return { ok: false, retryAfter: Math.ceil((THROTTLE_WINDOW_MS - (now - hits[0])) / 1000) };
  }
  hits.push(now);
  _throttle.set(ip, hits);
  if (_throttle.size > 5000) {
    for (const [k, v] of _throttle) if (!v.length || now - v[v.length - 1] > THROTTLE_WINDOW_MS) _throttle.delete(k);
  }
  return { ok: true };
}

function corsHeaders() {
  return {
    'Access-Control-Allow-Origin': '*',
    'Access-Control-Allow-Methods': 'POST, OPTIONS',
    'Access-Control-Allow-Headers': 'Content-Type, Authorization',
    'Cache-Control': 'no-store'
  };
}

// Single, guarded chat/completions call to one provider+model. Returns
// { ok, status, reply } — `status` lets the caller rotate on 429.
async function tryProvider(provider, messages, temperature, maxTokens) {
  const url = provider.base + (provider.base.endsWith('/chat/completions') ? '' : '/chat/completions');
  let res;
  try {
    res = await fetchWithTimeout(url, {
      method: 'POST',
      headers: aiHeaders(provider, provider.key),
      body: JSON.stringify({ model: provider.models[0], messages, temperature, max_tokens: maxTokens })
    });
  } catch (e) {
    if (e && e.isTimeout) return { ok: false, status: 504, error: 'timeout' };
    return { ok: false, status: 0, error: 'network:' + (e.message || 'fetch failed') };
  }
  if (!res.ok) {
    // R10: 2.1 retried here with a byte-identical body while the comment
    // claimed it was "retrying without tools" — this request never sent tools
    // in the first place, so the retry could only ever reproduce the same
    // failure at double the latency. Rotate to the next provider instead.
    return { ok: false, status: res.status, error: 'HTTP_' + res.status };
  }
  try {
    const data = await res.json();
    const reply = data.choices && data.choices[0] && data.choices[0].message && data.choices[0].message.content;
    return { ok: !!reply, status: res.status, reply: reply ? String(reply).trim() : null };
  } catch (e) {
    return { ok: false, status: res.status, error: 'parse:' + (e.message || 'json') };
  }
}

// Rotate providers on 429 (rate-limit): move the failing provider to the back
// and pick the next free one. Each rotation retries at most once per provider.
async function chatWithFallback(providers, messages) {
  const temperature = 0.6, maxTokens = 1200;
  const queue = providers.slice();
  let attempts = 0;
  while (queue.length && attempts < providers.length * 2) {
    attempts++;
    const provider = queue.shift();
    const r = await tryProvider(provider, messages, temperature, maxTokens);
    if (r.ok && r.reply) return { ok: true, reply: r.reply, provider: provider.id };
    if (r.status === 429 || r.status === 504) {
      // rate-limited or timed out → rotate to the next provider and retry
      queue.push(provider);
      continue;
    }
    // hard error (bad key, model missing, provider down) → just move on
  }
  return { ok: false };
}

// SSE passthrough: stream deltas from the first available provider.
async function streamPassthrough(req, res, providers, messages, identity) {
  const temperature = 0.6, maxTokens = 1200;
  res.writeHead(200, {
    'Content-Type': 'text/event-stream; charset=utf-8',
    'Cache-Control': 'no-cache, no-transform',
    Connection: 'keep-alive',
    'Access-Control-Allow-Origin': '*'
  });
  const queue = providers.slice();
  const send = (obj) => res.write('data: ' + JSON.stringify(obj) + '\n\n');
  let attempts = 0;
  while (queue.length && attempts < providers.length * 2) {
    attempts++;
    const provider = queue.shift();
    const url = provider.base + (provider.base.endsWith('/chat/completions') ? '' : '/chat/completions');
    let up;
    try {
      up = await fetchWithTimeout(url, {
        method: 'POST',
        headers: aiHeaders(provider, provider.key),
        body: JSON.stringify({ model: provider.models[0], messages, temperature, max_tokens: maxTokens, stream: true })
      });
    } catch (e) { continue; }
    if (up.status === 429) { queue.push(provider); continue; }
    if (!up.ok || !up.body) continue;
    const reader = up.body.getReader();
    const decoder = new TextDecoder();
    let buf = '';
    let content = '';
    try {
      while (true) {
        const { done, value } = await reader.read();
        if (done) break;
        buf += decoder.decode(value, { stream: true });
        const lines = buf.split('\n');
        buf = lines.pop() || '';
        for (const line of lines) {
          const t = line.trim();
          if (!t.startsWith('data:')) continue;
          const payload = t.slice(5).trim();
          if (payload === '[DONE]') { send({ done: true, provider: provider.id }); res.end(); return; }
          let json;
          try { json = JSON.parse(payload); } catch { continue; }
          const delta = json.choices && json.choices[0] && json.choices[0].delta && json.choices[0].delta.content;
          if (delta) { content += delta; send({ delta, provider: provider.id }); }
        }
      }
    } catch (e) { /* stream aborted */ }
    if (content) { send({ done: true, reply: content.trim(), provider: provider.id }); res.end(); return; }
    // stream produced nothing usable → try next provider
  }
  // Streaming unavailable everywhere — still answer with the free brain.
  send({ delta: freeBrain((messages[messages.length - 1] || {}).content || '') });
  send({ done: true });
  res.end();
}

module.exports = async (req, res) => {
  if (req.method === 'OPTIONS') {
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');
    return res.status(204).end();
  }
  if (req.method !== 'POST') return res.status(405).json({ error: 'POST only' });
  res.setHeader('Cache-Control', 'no-store');

  // R10a: only GemAir's own origins may spend the shared free provider keys.
  const origin = originAllowed(req);
  if (!origin.ok) {
    return res.status(403).json({ ok: false, error: 'origin_not_allowed', origin: origin.origin });
  }

  // R10b: per-IP throttle so one client cannot drain the free tier.
  const ip = clientIp(req);
  const gate = throttleCheck(ip);
  if (!gate.ok) {
    res.setHeader('Retry-After', String(gate.retryAfter));
    return res.status(429).json({
      ok: true,
      reply: `You're sending messages faster than the free core can serve them. Give me about ${gate.retryAfter} second(s) and try again — or add your own API key under Settings → Power user for unthrottled replies.`,
      free: true, throttled: true, retryAfter: gate.retryAfter
    });
  }

  let body = {};
  try { body = req.body || {}; } catch {}

  const messages = Array.isArray(body.messages) ? body.messages : [];
  if (!messages.length) return res.status(400).json({ error: 'messages required' });

  const lastUser = [...messages].reverse().find((m) => m && m.role === 'user');
  const prompt = lastUser && lastUser.content ? String(lastUser.content).trim() : '';

  // Per-identity fair-use (Section 0): enforce a daily cap; when hit, still
  // answer helpfully rather than erroring.
  const identity = identityFor(req, body);
  const { left } = fairUseLeft(identity);
  if (left <= 0) {
    const friendly = `You've reached the free core's daily message limit for today. It resets at midnight UTC — or you can add your own key under Settings → Power user to keep going with unlimited replies. Thanks for using GemAir!`;
    return res.json({ ok: true, reply: friendly, free: true, limited: true });
  }
  consumeFairUse(identity);

  // Streaming passthrough (SSE).
  if (body.stream === true) {
    const providers = availableProviders();
    if (providers.length) return streamPassthrough(req, res, providers, messages, identity);
    res.writeHead(200, {
      'Content-Type': 'text/event-stream; charset=utf-8',
      'Cache-Control': 'no-cache, no-transform',
      'Access-Control-Allow-Origin': '*'
    });
    res.write('data: ' + JSON.stringify({ delta: freeBrain(prompt), provider: 'free' }) + '\n\n');
    res.write('data: ' + JSON.stringify({ done: true }) + '\n\n');
    return res.end();
  }

  const providers = availableProviders();
  if (!providers.length) {
    // No key configured anywhere → answer with the free brain. Always ok:true,
    // never an error or a key prompt for the end-user.
    return res.json({ ok: true, reply: freeBrain(prompt), free: true, provider: 'free' });
  }

  const result = await chatWithFallback(providers, messages);
  if (result.ok) return res.json({ ok: true, reply: result.reply, provider: result.provider, free: providers.every((p) => p.free) });
  // Every provider failed (bad keys, providers down, …) — still answer the
  // user seamlessly with the free brain instead of surfacing an error.
  return res.json({ ok: true, reply: freeBrain(prompt), free: true, provider: 'free' });
};
